#theme = "modern"
theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"



[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"



[[block]]
block = "cpu"
interval = 1


[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "uptime"


#[[block]]
#block = "backlight"
#device = "intel_backlight"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "*-isa-*"
inputs = ["Core 0", "Core 1"]

[[block]]
block = "sound"


[[block]]
block = "time"
interval = 25
format = "%a %d/%m %R"
